In [1]:
import pandas as pd
import numpy as np
import plotly.express as px

In [3]:
df= pd.read_csv("social_media_engagement.csv")

In [4]:
df.nuniqu

post_id            100
platform             3
post_type            5
post_time           99
likes               93
comments            85
shares              96
post_day             7
sentiment_score      3
dtype: int64

In [8]:
px.bar(x=df.post_type, y=df.likes, width=1000,height=1000)

In [25]:
px.bar(x=df.post_type, y=df.likes, title="First Graph",text_auto=True, color=df.comments
       , color_discrete_map={"Facebook":"black","Instagram":"red","Twitter":"blue"}, hover_data=[df.post_day,df.sentiment_score])

In [27]:
px.bar(y=df.post_type, x=df.likes, title="First Graph",text_auto=True, color=df.comments
       , color_discrete_map={"Facebook":"black","Instagram":"red","Twitter":"blue"}, hover_data=[df.post_day,df.sentiment_score]
      ,orientation ="h")

In [28]:
px.bar(y=df.post_type, x=df.likes, title="First Graph",text=df.likes, color=df.comments
       , color_discrete_map={"Facebook":"black","Instagram":"red","Twitter":"blue"}, hover_data=[df.post_day,df.sentiment_score]
      ,orientation ="h")

In [41]:
px.bar(x=df.post_type, y=[df.likes,df.comments, df.shares], title="First Graph",text=df.likes, color=df.platform
       , color_discrete_map={"Facebook":"black","Instagram":"red","Twitter":"blue"}, hover_data=[df.post_day,df.sentiment_score]
      ,pattern_shape=df.sentiment_score, barmode="relative")

In [43]:
px.bar(x=df.post_id, y=[df.comments, df.shares], barmode="relative")

In [46]:
data= pd.DataFrame({"c":["A","B","C"], "v":[10,-20,30]})
px.bar(x=data.c, y=data.v, orientation="h")

In [54]:
px.scatter(x=df.comments,y=df.likes, title="ABC", height=700, width=900, color=df.shares, symbol=df.platform)

In [64]:
px.scatter(x=df.comments,y=df.likes, title="ABC", size=df.shares, color=df.post_type
          ,facet_row=df.post_day, facet_col=df.sentiment_score)

In [60]:
px.scatter_3d(x=df.likes,  y=df.comments, z=df.shares)

In [65]:
df

,post_id,platform,post_type,post_time,likes,comments,shares,post_day,sentiment_score
0,1,Facebook,image,8/17/2023 14:45,2121,474,628,Thursday,positive
1,2,Facebook,carousel,5/14/2023 0:45,3660,432,694,Sunday,neutral
2,3,Instagram,poll,2/21/2023 16:15,4955,408,688,Tuesday,negative
3,4,Twitter,image,11/16/2023 0:45,1183,90,187,Thursday,negative
4,5,Twitter,video,5/23/2023 0:30,3499,247,286,Tuesday,positive
...,...,...,...,...,...,...,...,...,...
95,96,Instagram,carousel,7/12/2023 17:45,36,294,911,Wednesday,positive
96,97,Twitter,video,10/27/2023 23:45,314,108,458,Friday,neutral
97,98,Twitter,text,8/5/2023 8:45,229,179,38,Saturday,positive
98,99,Instagram,poll,12/29/2023 12:15,5000,500,204,Friday,positive
99,100,Instagram,image,6/6/2023 21:00,4483,357,25,Tuesday,neutral

In [69]:

data = pd.DataFrame(sum1)

In [74]:
sum1= df.groupby("platform", as_index=False)["likes", "comments","shares"].sum()
sum1

<ipython-input-74-1ed413b278c7>:1: FutureWarning:

Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.

    platform   likes  comments  shares
0   Facebook   86392      7965   15180
1  Instagram  107994      8368   18906
2    Twitter   43795      3933    7479

In [70]:
data

            likes
platform
Facebook    86392
Instagram  107994
Twitter     43795

In [72]:
px.scatter_matrix(dimensions=[df.comments,df.shares,df.likes], color=df.platform, size= df.shares)

In [85]:
fig= px.pie(data_frame=sum1, values="likes" ,names="platform", color_discrete_sequence=["black","orange", "green"])
fig.update_traces(textinfo= "percent+label", textposition="outside", pull=[0.1,0.1,0.1])
fig

In [90]:
px.line(data_frame=df, x="platform", y="likes", color=df.platform, markers=True)

In [91]:
pd.get_dummies(df)

,post_id,likes,comments,shares,platform_Facebook,platform_Instagram,platform_Twitter,post_type_carousel,post_type_image,post_type_poll,...,post_day_Friday,post_day_Monday,post_day_Saturday,post_day_Sunday,post_day_Thursday,post_day_Tuesday,post_day_Wednesday,sentiment_score_negative,sentiment_score_neutral,sentiment_score_positive
0,1,2121,474,628,1,0,0,0,1,0,...,0,0,0,0,1,0,0,0,0,1
1,2,3660,432,694,1,0,0,1,0,0,...,0,0,0,1,0,0,0,0,1,0
2,3,4955,408,688,0,1,0,0,0,1,...,0,0,0,0,0,1,0,1,0,0
3,4,1183,90,187,0,0,1,0,1,0,...,0,0,0,0,1,0,0,1,0,0
4,5,3499,247,286,0,0,1,0,0,0,...,0,0,0,0,0,1,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,96,36,294,911,0,1,0,1,0,0,...,0,0,0,0,0,0,1,0,0,1
96,97,314,108,458,0,0,1,0,0,0,...,1,0,0,0,0,0,0,0,1,0
97,98,229,179,38,0,0,1,0,0,0,...,0,0,1,0,0,0,0,0,0,1
98,99,5000,500,204,0,1,0,0,0,1,...,1,0,0,0,0,0,0,0,0,1
99,100,4483,357,25,0,1,0,0,1,0,...,0,0,0,0,0,1,0,0,1,0